<?php
return [
    'adminEmail' => 'admin@example.com',

    'authCompanyIds' => [],
    'authVenueIds' => [],
    'doorArr'      => [
        'basketball'=>['223229130-2','223229130-1'],
        'badminton' =>['223262658-1','223229130-2'],
        'classroomTwo'=>['223229120-2','223229120-1'],
        'classroomOne'=>['2232625892-1','2232625892-2'],
    ],
    'Bilingual'=>[
        '课不存在'=>['en'=>'Class doesn\'t exist.','zh'=>'课不存在'],
        '已打上课卡'=>['en'=>'Class card has been played','zh'=>'已打上课卡'],
        '上课打卡成功'=>['en'=>'Class clocked in successfully','zh'=>'上课打卡成功'],
        '下课打卡成功'=>['en'=>'Success in punching the class','zh'=>'上课打卡成功'],


    ],
    'class'=>[
            '哈他瑜伽'=> 'Hata Yoga(L)',
            '塑形瑜伽'=> 'Hatha Yoga(L)',
            '体位呼吸法'=>'Asana Pranayama',
            '舞韵瑜伽'=>'Yoga(M)',
            '和缓瑜伽'=>'Gentle Yoga(M)',
            '空中瑜伽'=>'Body Fly(M)',
            '正念冥想' =>'Yoga（M）',
            '基础迈索尔' =>'Mysore（M）',
            '阴阳瑜伽' =>'Yinyang Yoga（M）',
            '拜日式'=> 'Sun Series（M）',
            '艾扬格瑜伽'=> 'Iyengar Yoga',
            '阴瑜伽'=> 'Yin Yoga（M）',
            '瑜伽疗法'=>'Yoga Therapy（M）',
            '腰骨盆理疗'=>'Yoga Therapy（M）',
            '肩颈理疗'=>'Yoga Therapy（M）' ,
            '足膝理疗'=>'Yoga Therapy（M）',
            '热瑜伽26式'=>'Hot Yoga（M）',
            '身体平衡'=> 'Balance（M）',
            '流瑜伽'=> 'Vinyasa（H）',
            '阿斯汤加瑜伽' =>'Ashtanga Yaga（H）',
            '活力瑜伽' =>'Dynamic Yoga（H）',
            '普拉提' =>'Pilates（H）',
            '节奏瑜伽'=> 'Rhythmic Yoga（H）',
            '火箭瑜伽' =>'Rocket Yoga（H）',
            '宝莱坞舞'=> 'BollyWood（M）',
            '印度舞' =>'India Dance（M）',
            '街舞' =>'Hip-Hop（M）',
            '舞蹈' =>'Fusion Dance（M）',
//            'Mordance',
//            'Megadanz',
//            'Bodyjam（M）',
//            'Pop Dance',
            '搏击健身操' =>'Piloxing',
            '体能有氧' =>'NTC（M）',
            '炫舞'=> 'X-Dance（M）',
            '减肥操' =>'Attack（M）',
            '蹦床'=>'Ubound',
            '杠铃操' =>'BodyPump（M）',
            '搏击操'=> 'BodyCombat（M）',
            '爵士舞' =>'Jazz（M）',
            '太极'=> 'Tai Ji(M)',
            '肚皮舞'=> 'BellyDance（M）',
            '中国舞韵' =>'Dance（M）',
            '当代舞'=>'Modern Dance（M）',
            '古典舞' =>'Classical Dance(M)',
            '民族舞' =>'Folk Dance（M）',
            '芭蕾形体' =>'Ballet（M）',
            '拉丁舞' =>'Latin（M）',
            '伦巴舞' =>'Rumba（M）',
//            'Bodyjam（M）',
            '动感单车' =>'Spring（M）',
    ],
];
